name=tarfs
version=0.1.0
author=Viacheslav Logunov <vvb333007@gmail.com>
maintainer=Viacheslav Logunov <vvb333007@gmail.com>
license=MMIT
sentence=This library adds support for TARFS filesystem to your ESP32 sketch
paragraph=This library adds support for TARFS filesystem to your ESP32 sketch
category=Other
url=https://github.com/vvb333007/tarfs
architectures=esp32
includes=tarfs.h

