name=tarfs
version=0.1.1
author=Viacheslav Logunov <vvb333007@gmail.com>
maintainer=Viacheslav Logunov <vvb333007@gmail.com>
license=MMIT
sentence=Immutable FAST! Filesystem. This library adds support for TARFS filesystem to your ESP32 sketch
paragraph=Immutable TARFS: mmap-enabled read-only filesystem with support for hardlinks/symlinks, long names, UTF8,  and some other posix extensions.
category=Other
url=https://github.com/vvb333007/tarfs
architectures=esp32
includes=tarfs.h
